// Copyright © 2026 Fall Guy Consulting.
// Licensed under the Apache License, Version 2.0. See LICENSE.apache at the
// repo root, or http://www.apache.org/licenses/LICENSE-2.0.

package signal

import (
	"fmt"
	"strings"
)

// canonicalEmitPatterns enumerates every valid emit-shape TypePath in
// the canonical taxonomy. Patterns ending in "*" are prefix patterns
// (the "*" matches one or more slash-delimited segments). The middle
// position of attribute/<key>/changed is intentionally a single
// segment captured by attributeMidSuffix below.
//
// Adding a new pattern here must travel alongside a new payload
// schema in payloads.go and an update to concepts/signal.md.
var canonicalEmitPatterns = []string{
	"terminal/success",
	"terminal/error/*",
	"terminal/park/snooze",
	"terminal/park/await_callback",
	"terminal/infra/*",
	"transient/retry/*",
	"transient/heartbeat_missed",
	"transient/await_async",
	"attribute/*/changed",
	"event/*",
	"message/*",
}

// ValidateTypePath returns nil if t is a legal emit-shape path under
// the canonical taxonomy. Exact patterns (no trailing "*") must match
// verbatim; prefix patterns (trailing "*") accept one-or-more
// slash-delimited tail segments. The special attribute/<key>/changed
// shape is matched by checking the "/changed" suffix with a
// non-empty middle key segment.
//
// Returns a descriptive error naming the offending path on rejection.
func ValidateTypePath(t TypePath) error {
	s := string(t)
	if s == "" {
		return fmt.Errorf("invalid signal type-path: empty")
	}
	if matchesCanonical(s, false) {
		return nil
	}
	return fmt.Errorf("invalid signal type-path: %q (not in canonical taxonomy)", s)
}

// ValidateSubscriptionType returns nil if t is a legal subscription
// pattern. Subscription patterns may be exact emit-shape paths OR a
// trailing-"*" prefix that itself matches some prefix of the
// canonical taxonomy (e.g., "terminal/error/*", "terminal/*",
// "event/*"). Positional wildcards (e.g., "terminal/*/foo",
// "*/error/*") are explicitly rejected at the operator-template
// surface with a precise error message — operators must express
// such patterns via CEL when:.
//
// Asymmetry note: the cascade matcher
// (`code:graph/node/subscription_edges.go::appendMatches`) DOES accept
// positional `*` at runtime, but exclusively for runtime-synthesized
// implicit subscriptions (e.g. `attribute/*/changed` autogenerated
// from a bare-attribute substitution `{{nodes.X.attribute}}`). Those
// patterns never travel through the operator template surface, so
// they bypass this validator by construction. Operator-declared
// subscriptions are constrained to trailing-only `*`.
func ValidateSubscriptionType(t TypePath) error {
	s := string(t)
	if s == "" {
		return fmt.Errorf("invalid subscription type: empty")
	}
	if positionalWildcard(s) {
		return fmt.Errorf(
			"invalid subscription type: %q (positional wildcards not supported; use trailing-*)", s)
	}
	if matchesCanonical(s, true) {
		return nil
	}
	return fmt.Errorf("invalid subscription type: %q (not in canonical taxonomy)", s)
}

// positionalWildcard reports whether a "*" appears anywhere other
// than the last character of the string.
func positionalWildcard(s string) bool {
	idx := strings.IndexByte(s, '*')
	if idx < 0 {
		return false
	}
	return idx != len(s)-1
}

// matchesCanonical reports whether s matches any pattern in
// canonicalEmitPatterns. When allowTrailingWildcard is true, s itself
// may end in "*"; in that case the match succeeds if the prefix
// preceding the "*" is a prefix of any canonical pattern (e.g.,
// "terminal/*" matches because canonicalEmitPatterns has paths
// starting with "terminal/"; "event/*" matches verbatim).
func matchesCanonical(s string, allowTrailingWildcard bool) bool {
	// Subscription-side trailing-* matching first (only when permitted).
	if allowTrailingWildcard && strings.HasSuffix(s, "*") {
		prefix := strings.TrimSuffix(s, "*")
		if prefix == "" {
			return false
		}
		for _, p := range canonicalEmitPatterns {
			// Strip trailing "*" off canonical prefix patterns so we
			// compare apples to apples.
			canon := strings.TrimSuffix(p, "*")
			// Either the subscription prefix is a prefix of the
			// canonical exact path (e.g. "terminal/" prefixes
			// "terminal/success"); or the canonical prefix is a prefix
			// of the subscription prefix (e.g. "terminal/error/" is a
			// prefix of "terminal/error/http/").
			if strings.HasPrefix(canon, prefix) || strings.HasPrefix(prefix, canon) {
				return true
			}
		}
		return false
	}

	// Exact-match emit-shape paths.
	for _, p := range canonicalEmitPatterns {
		// Special-case attribute/<key>/changed — the middle is a
		// single non-empty segment and the suffix must be /changed.
		if p == "attribute/*/changed" {
			const prefix = "attribute/"
			const suffix = "/changed"
			if len(s) < len(prefix)+len(suffix) {
				continue
			}
			if !strings.HasPrefix(s, prefix) || !strings.HasSuffix(s, suffix) {
				continue
			}
			middle := s[len(prefix) : len(s)-len(suffix)]
			if middle == "" || strings.Contains(middle, "/") {
				continue
			}
			return true
		}
		if !strings.HasSuffix(p, "*") {
			if s == p {
				return true
			}
			continue
		}
		// Prefix pattern — the candidate must start with the literal
		// prefix AND have at least one trailing segment.
		canonPrefix := strings.TrimSuffix(p, "*")
		if !strings.HasPrefix(s, canonPrefix) {
			continue
		}
		tail := s[len(canonPrefix):]
		if tail == "" {
			// "terminal/error" without a leaf class is not a valid
			// emit shape; require at least one tail segment.
			continue
		}
		// Catch-all: any non-empty tail is fine (terminal/error/<class>,
		// terminal/infra/<reason>, transient/retry/<n>/<class>,
		// event/<name>, message/<kind>/<sender_kind>/<target>).
		return true
	}
	return false
}
