// ClaimProducer interface — the rimsky-side contract every
// claim-producer implementation satisfies. Per spec
// docs/specs/2026-05-04-service-protocol-contract.md §2.
//
// Standard producer implementations live in standalone binaries under
// stores/ and rimsky talks to them via the gRPC client in
// foundation/integration/remote/. Type assertions to a concrete producer
// from any rimsky package are forbidden — the ClaimProducer interface is
// the only contract.
//
// Lifecycle events live in a separate LifecycleSubscriber interface
// (lifecycle.go in this package; spec §3). A producer binary that wishes
// to react to control-plane events implements both interfaces and
// declares both protocols in rimsky.yml.

package locks

import "context"

// ClaimProducer is the universal interface every claim-producer
// implementation satisfies.
//
// Four runtime verbs (Open / Commit / Abandon / Release) plus one
// startup-handshake verb (Capabilities). Each verb carries a
// rimsky-generated claim_id. The producer may key its internal state by
// claim_id, by address, by both, or by neither.
//
// Claim disposition (what Commit / Abandon mean for the producer's own
// state — publish staging, delete an items-table row, release-to-back,
// etc.) is governed entirely by per-producer config. Rimsky carries only
// the success/failure binary: success → Commit; failure → Abandon.
//
// @blessed-invariant 9a: Lock state lives only in the persistence layer.
//
//	No ClaimProducer implementation persists lock state. Producers may
//	persist *data* state (e.g. items-table flips, staging metadata), but
//	the question "is anyone holding lock X" is answered exclusively by
//	rimsky_lock_holders (managed via foundation/persistence/<driver>/
//	lock_holders.go).
//
// @blessed-invariant 9b: ClaimProducers do not internally serialize on
// lock-shaped predicates. The reader-lease serialization pattern is not
// a valid implementation choice for staged_async; honest support
// requires snapshot delegation or native MVCC pass-through.
type ClaimProducer interface {
	// Name returns the operator-configured producer name (matches
	// claim_producers.<name> in rimsky.yml). Rimsky-side identifier;
	// not transported over the wire.
	Name() string

	// Capabilities reports the producer's advertised capability struct.
	// Called once per producer per rimsky process at startup; rimsky
	// caches the result and validates it against the operator's
	// declared envelope (must be subset).
	Capabilities(ctx context.Context) (Capabilities, error)

	// Open creates whatever producer-internal state the (intent,
	// realized write_semantics) combination requires (staging area,
	// snapshot, MVCC transaction, picked-item flip, or nothing) and
	// returns the producer-supplied address the executor will use on
	// the data path. The supervisor calls Open inside the rimsky-side
	// acquisition transaction; the producer's own state mutation runs
	// in its own transaction, decoupled.
	//
	// claim_id is generated by the supervisor before the call; the
	// producer may record it before any state mutation so its sweep
	// can identify orphans.
	//
	// The returned ClaimResult.RealizedWriteSemantics MUST be a member
	// of the producer's Capabilities.WriteSemanticsEnvelope and MUST
	// be uniform across byte-equal-Scope claims.
	//
	// Producers that may have nothing to give right now (e.g. an empty
	// items-table queue) return OpenOutcome{Available: false}. Rimsky
	// rolls back the dispatch tx and may retry on the next scheduler
	// tick. Producer-side faults flow as gRPC error status codes (or
	// wrapped Go errors), not as Available: false.
	Open(ctx context.Context, claimID ClaimID, spec ClaimSpec) (OpenOutcome, error)

	// Commit signals that the consumer of the claim succeeded. The
	// producer decides what to do with its own state (publish staging
	// into live, delete the items-table row, release-to-back, etc.)
	// per its own configuration. For sync rw, typically a no-op.
	Commit(ctx context.Context, claimID ClaimID, scope []byte, address []byte) error

	// Abandon signals that the consumer of the claim failed. The
	// producer decides what to do with its own state per its own
	// configuration. Not called for read-only claims and not called
	// by the orphan reaper in default behavior.
	// address may be empty when Open's response was lost.
	Abandon(ctx context.Context, claimID ClaimID, scope []byte, address []byte) error

	// Release tears down producer-internal read state created at Open.
	// Sync producers typically no-op; relevant when the producer
	// registered per-claim state at Open (staged_async, etc.).
	Release(ctx context.Context, claimID ClaimID, scope []byte, address []byte) error
}

// Store is a deprecated alias for ClaimProducer kept for transitional
// compatibility during the layer-crystallization rollout. New code MUST
// use ClaimProducer directly.
//
// Deprecated: use ClaimProducer.
type Store = ClaimProducer
