// Copyright © 2026 Fall Guy Consulting.
// Dual-licensed under AGPL-3.0-or-later or a Fall Guy Consulting commercial
// license. See LICENSE.agpl and COPYRIGHT at the repo root.

package conformance

import (
	"testing"

	"github.com/rimsky-ai/rimsky-core/lib/foundation/persistence"
)

type RawQueryRow = map[string]any

func Suite(
	t *testing.T,
	factory func(*testing.T) persistence.Database,
	rawExec func(t *testing.T, d persistence.Database, sql string, args ...any),
	rawQuery func(t *testing.T, d persistence.Database, sql string, args ...any) []RawQueryRow,
) {
	t.Helper()
	t.Run("DispatchClaimRelease", func(t *testing.T) { testDispatchClaimRelease(t, factory(t)) })
	t.Run("DispatchReleaseClaimSkipsTerminalRun", func(t *testing.T) { testDispatchReleaseClaimSkipsTerminalRun(t, factory(t)) })
	t.Run("VerifyBeforeRunRead", func(t *testing.T) { testVerifyBeforeRunRead(t, factory(t)) })
	t.Run("MigrationIdempotency", func(t *testing.T) { testMigrationIdempotency(t, factory(t)) })
	t.Run("CoordinatorSchedulerTick", func(t *testing.T) { testCoordinatorSchedulerTick(t, factory(t)) })
	t.Run("ForeignKeyCascade", func(t *testing.T) { testForeignKeyCascade(t, factory(t)) })
	t.Run("ClaimScopeByteEquality", func(t *testing.T) { testClaimScopeByteEquality(t, factory(t)) })
	t.Run("OrphanCutoffTime", func(t *testing.T) { testOrphanCutoffTime(t, factory(t)) })
	t.Run("ReaperSkipsParkedHolder", func(t *testing.T) { testReaperSkipsParkedHolder(t, factory(t)) })
	t.Run("SweepExecutorDeadlinesSkipsParkedRow", func(t *testing.T) { testSweepExecutorDeadlinesSkipsParkedRow(t, factory(t)) })
	t.Run("RenewExpiryForHolderRun", func(t *testing.T) { testRenewExpiryForHolderRun(t, factory(t)) })
	t.Run("CoHolderInsertIdempotent", func(t *testing.T) { testCoHolderInsertIdempotent(t, factory(t)) })
	t.Run("TxAtomicity", func(t *testing.T) { testTxAtomicity(t, factory(t)) })
	t.Run("AcquisitionTxAtomicity", func(t *testing.T) { testAcquisitionTxAtomicity(t, factory(t)) })
	t.Run("ClaimHandleLockForUpdateSerializesConcurrentTx", func(t *testing.T) { testClaimHandleLockForUpdateSerializesConcurrentTx(t, factory(t)) })
	t.Run("AdvisoryLockConcurrentAcquisitionSmoke", func(t *testing.T) { testAdvisoryLockConcurrentAcquisitionSmoke(t, factory(t)) })
	t.Run("PublisherSubscriptionLifecycle", func(t *testing.T) { testPublisherSubscriptionLifecycle(t, factory(t)) })
	t.Run("QueueInTxAndDispatchNode", func(t *testing.T) { testQueueInTxAndDispatchNode(t, factory(t)) })
	t.Run("SelectCandidatesSkipsPausedInstances", func(t *testing.T) { testSelectCandidatesSkipsPausedInstances(t, factory(t)) })
	t.Run("SelectCandidatesSkipsTerminatedInstances", func(t *testing.T) { testSelectCandidatesSkipsTerminatedInstances(t, factory(t)) })
	t.Run("SelectCandidatesKeysetCursor", func(t *testing.T) { testSelectCandidatesKeysetCursor(t, factory(t)) })
	t.Run("SelectCandidatesLateBindMixedStores", func(t *testing.T) { testSelectCandidatesLateBindMixedStores(t, factory(t)) })
	t.Run("SelectCandidatesLateBindExecutor", func(t *testing.T) { testSelectCandidatesLateBindExecutor(t, factory(t)) })
	t.Run("SelectCandidatesNoLateBindProxyLeavesStaticFilterUnchanged", func(t *testing.T) {
		testSelectCandidatesNoLateBindProxyLeavesStaticFilterUnchanged(t, factory(t))
	})
	t.Run("ClaimHandlesUpdateClaimScope", func(t *testing.T) { testClaimHandlesUpdateClaimScope(t, factory(t)) })

	t.Run("RunScopeLifecycle", func(t *testing.T) {
		t.Run("CreateMainAndChild", func(t *testing.T) { testRunScopeCreateMainAndChild(t, factory(t)) })
		t.Run("CloseStampsClosedAt", func(t *testing.T) { testRunScopeCloseStampsClosedAt(t, factory(t)) })
		t.Run("AffirmAfterCloseErrors", func(t *testing.T) { testRunScopeAffirmAfterCloseErrRunScopeClosed(t, factory(t)) })
		t.Run("FanoutPartitionUniqueness", func(t *testing.T) { testRunScopeFanoutPartitionUniqueness(t, factory(t)) })
		t.Run("ListParentChain", func(t *testing.T) { testRunScopeListParentChain(t, factory(t)) })
		t.Run("KindDerivableFromStructuralFields", func(t *testing.T) { testRunScopeKindDerivableFromStructuralFields(t, factory(t)) })
	})
	t.Run("SettlingSignalTypeNullNotEmptyStringSentinel", func(t *testing.T) { testSettlingSignalTypeNullNotEmptyStringSentinel(t, factory(t)) })
	t.Run("FrameDerivedStateTerminatedOnKill", func(t *testing.T) { testFrameDerivedStateTerminatedOnKill(t, factory(t)) })
	t.Run("FrameDerivedStateGenuineFailureStaysFailed", func(t *testing.T) { testFrameDerivedStateGenuineFailureStaysFailed(t, factory(t)) })
	t.Run("RunScopeListTreeDeepestFirst", func(t *testing.T) { testRunScopeListTreeDeepestFirst(t, factory(t)) })
	t.Run("RunInFlightLookup", func(t *testing.T) {
		t.Run("SingleRowPerScopePerNode", func(t *testing.T) { testInFlightLookupSingleRowPerScopePerNode(t, factory(t)) })
		t.Run("NoFalsePositiveAcrossScopes", func(t *testing.T) { testInFlightLookupNoFalsePositiveAcrossScopes(t, factory(t)) })
		t.Run("ReturnsNoneWhenAbsent", func(t *testing.T) { testInFlightLookupReturnsNoneWhenAbsent(t, factory(t)) })
		t.Run("DeterministicWithMultipleCoexistingPendings", func(t *testing.T) {
			testInFlightLookupDeterministicWithMultipleCoexistingPendings(t, factory(t))
		})
	})
	t.Run("ListInFlightRunStates", func(t *testing.T) {
		t.Run("PerNodeStates", func(t *testing.T) { testListInFlightRunStates(t, factory(t)) })
	})
	t.Run("ListRunsForInstanceByStates", func(t *testing.T) { testListRunsForInstanceByStates(t, factory(t)) })
	t.Run("NodeBatchLookups", func(t *testing.T) {
		t.Run("GetRunSummaryForNodes", func(t *testing.T) { testGetRunSummaryForNodes(t, factory(t)) })
		t.Run("GetLatestRunForNodes", func(t *testing.T) { testGetLatestRunForNodes(t, factory(t)) })
	})
	t.Run("TemplateTagsConditionalWrites", func(t *testing.T) {
		t.Run("InsertIfAbsent", func(t *testing.T) { testTemplateTagsInsertIfAbsent(t, factory(t)) })
		t.Run("UpdateIfExists", func(t *testing.T) { testTemplateTagsUpdateIfExists(t, factory(t)) })
	})
	t.Run("RunStateWritesIsolated", func(t *testing.T) {
		t.Run("UpdateState", func(t *testing.T) { testRunStateWritesIsolated_UpdateState(t, factory(t)) })
		t.Run("UpdateStateWritesNoAuditEvent", func(t *testing.T) { testRunStateWritesIsolated_UpdateStateWritesNoAuditEvent(t, factory(t)) })
		t.Run("BumpLastProgressAt", func(t *testing.T) { testRunStateWritesIsolated_BumpLastProgressAt(t, factory(t)) })
		t.Run("ResetFailedTerminalSettlingSignalType", func(t *testing.T) { testRunStateWritesIsolated_ResetFailedTerminalSettlingSignalType(t, factory(t)) })
		t.Run("RemoveForNodeInTx", func(t *testing.T) { testRunStateWritesIsolated_RemoveForNodeInTx(t, factory(t)) })
		t.Run("GetParkedByNode", func(t *testing.T) { testRunStateWritesIsolated_GetParkedByNode(t, factory(t)) })
		t.Run("NodeAttributesGetLatestByNode", func(t *testing.T) { testRunStateWritesIsolated_NodeAttributesGetLatestByNode(t, factory(t)) })
	})
	t.Run("ScopeKeyedRunStateOpsIsolated", func(t *testing.T) {
		t.Run("GetMostRecentRunForNodeInScope", func(t *testing.T) { testScopeKeyedOps_GetMostRecentRunForNodeInScope(t, factory(t)) })
		t.Run("HasAdvancedSiblingInScope", func(t *testing.T) { testScopeKeyedOps_HasAdvancedSiblingInScope(t, factory(t)) })
		t.Run("ListPendingRunsInScopeForNodes", func(t *testing.T) { testScopeKeyedOps_ListPendingRunsInScopeForNodes(t, factory(t)) })
		t.Run("HasLaterCascadePending", func(t *testing.T) { testScopeKeyedOps_HasLaterCascadePending(t, factory(t)) })
		t.Run("GetPriorRunBySequence", func(t *testing.T) { testScopeKeyedOps_GetPriorRunBySequence(t, factory(t)) })
		t.Run("DeletePriorCascadeStales", func(t *testing.T) { testScopeKeyedOps_DeletePriorCascadeStales(t, factory(t)) })
		t.Run("GetPriorCascadeStaleNotClaimed", func(t *testing.T) { testScopeKeyedOps_GetPriorCascadeStaleNotClaimed(t, factory(t)) })
		t.Run("GetMostRecentSettledRun", func(t *testing.T) { testScopeKeyedOps_GetMostRecentSettledRun(t, factory(t)) })
		t.Run("SnapshotBagForNewRun", func(t *testing.T) { testScopeKeyedOps_SnapshotBagForNewRun(t, factory(t)) })
	})
	t.Run("RecoveryAwareDispatch", func(t *testing.T) { testRecoveryAwareDispatch(t, factory(t)) })
	t.Run("RecoveryDispositionStamps", func(t *testing.T) { testRecoveryDispositionStamps(t, factory(t)) })
	t.Run("SelectCandidatesSkipsUndrainedWaitSet", func(t *testing.T) { testSelectCandidatesSkipsUndrainedWaitSet(t, factory(t)) })
	t.Run("ScratchMissingRowContract", func(t *testing.T) { testScratchMissingRowContract(t, factory(t)) })
	t.Run("NodeAttributesMergeDelta", func(t *testing.T) { testNodeAttributesMergeDelta(t, factory(t)) })
	t.Run("NodeAttributesGetPriorRunData", func(t *testing.T) { testNodeAttributesGetPriorRunData(t, factory(t)) })
	t.Run("NodeAttributesPerRunInsertByRun", func(t *testing.T) { testNodeAttributesPerRunInsertByRun(t, factory(t)) })
	t.Run("NodeAttributesGetLatestByNode", func(t *testing.T) { testNodeAttributesGetLatestByNode(t, factory(t)) })
	t.Run("NodeAttributesCascadeDeleteWithRun", func(t *testing.T) { testNodeAttributesCascadeDeleteWithRun(t, factory(t), rawExec) })
	t.Run("NodeAttributesPerRunDenormConsistency", func(t *testing.T) { testNodeAttributesPerRunDenormConsistency(t, factory(t)) })
	t.Run("NodeRunSummaryBucketMapping", func(t *testing.T) { testNodeRunSummaryBucketMapping(t, factory(t)) })
	t.Run("InstancesFindAnyByInstanceKey", func(t *testing.T) { testInstancesFindAnyByInstanceKey(t, factory(t)) })
	t.Run("InstancesCreateConflictErrorsDistinguishIDFromKey", func(t *testing.T) { testInstancesCreateConflictErrorsDistinguishIDFromKey(t, factory(t)) })
	t.Run("InstancesListPaginationSurvivesCursorRowDeletion", func(t *testing.T) { testInstancesListPaginationSurvivesCursorRowDeletion(t, factory(t)) })
	t.Run("InstancesAttributeOverridesRoundTrip", func(t *testing.T) { testInstancesAttributeOverridesRoundTrip(t, factory(t)) })
	t.Run("InstancesAttributeOverridesDefaultsEmpty", func(t *testing.T) { testInstancesAttributeOverridesDefaultsEmpty(t, factory(t)) })
	t.Run("InstancesDeleteCascadeRunScopeTree", func(t *testing.T) {
		testInstancesDeleteCascadeRunScopeTree(t, factory(t), rawQuery)
	})
	t.Run("CreateChildNodeRunRefusesClosedScope", func(t *testing.T) { testCreateChildNodeRunRefusesClosedScope(t, factory(t)) })
	t.Run("LifecycleIdempotencyListByClaimProducer", func(t *testing.T) { testLifecycleIdempotencyListByClaimProducer(t, factory(t)) })
	t.Run("EventsListDescending", func(t *testing.T) { testEventsListDescending(t, factory(t)) })
	t.Run("EventsListAuthPayloadFilters", func(t *testing.T) { testEventsListAuthPayloadFilters(t, factory(t)) })
	t.Run("EventsListPagination", func(t *testing.T) { testEventsListPagination(t, factory(t)) })
	t.Run("MessagesListByFrameID", func(t *testing.T) { testMessagesListByFrameID(t, factory(t)) })
	t.Run("MessagesListPendingForInstanceReturnsAllPending", func(t *testing.T) { testMessagesListPendingForInstanceReturnsAllPending(t, factory(t)) })
	t.Run("MessagesListBySender", func(t *testing.T) { testMessagesListBySender(t, factory(t)) })
	t.Run("MessagesListFiltersByType", func(t *testing.T) { testMessagesListFiltersByType(t, factory(t)) })
	t.Run("MessagesMarkDeliveredExcludesCancelled", func(t *testing.T) { testMessagesMarkDeliveredExcludesCancelled(t, factory(t)) })
	t.Run("MessagesScanNullPayload", func(t *testing.T) { testMessagesScanNullPayload(t, factory(t)) })
	t.Run("MessagesScanNonNullPayload", func(t *testing.T) { testMessagesScanNonNullPayload(t, factory(t)) })
	t.Run("MessagesListDeliveredAfterBefore", func(t *testing.T) { testMessagesListDeliveredAfterBefore(t, factory(t)) })
	t.Run("MessagesListCursorPagination", func(t *testing.T) { testMessagesListCursorPagination(t, factory(t)) })
	t.Run("WaitSet", func(t *testing.T) { testWaitSet(t, factory(t)) })
	t.Run("WaitSetTopicKindDistinctness", func(t *testing.T) { testWaitSetTopicKindDistinctness(t, factory(t)) })
	t.Run("WaitSetGateEvaluatorMethods", func(t *testing.T) { testWaitSetGateEvaluatorMethods(t, factory(t)) })
	t.Run("WaitSetFrameIsolation", func(t *testing.T) { testWaitSetFrameIsolation(t, factory(t)) })
	// @decision: claimant-guard-helper
	t.Run("ClaimantGuard", func(t *testing.T) {
		t.Run("HandleUpdates", func(t *testing.T) { testClaimantGuardHandleUpdates(t, factory(t)) })
		t.Run("HandleCounterBumps", func(t *testing.T) { testClaimantGuardHandleCounterBumps(t, factory(t)) })
		t.Run("HandlePromote", func(t *testing.T) { testClaimantGuardHandlePromote(t, factory(t)) })
		t.Run("HandleReassignHolder", func(t *testing.T) { testClaimantGuardHandleReassignHolder(t, factory(t)) })
		t.Run("HandleUpdateNodeRunID", func(t *testing.T) { testClaimantGuardHandleUpdateNodeRunID(t, factory(t)) })
		t.Run("HandleDelete", func(t *testing.T) { testClaimantGuardHandleDelete(t, factory(t)) })
		t.Run("HandleDeleteIfExpired", func(t *testing.T) { testClaimantGuardHandleDeleteIfExpired(t, factory(t)) })
		t.Run("HolderRelease", func(t *testing.T) { testClaimantGuardHolderRelease(t, factory(t)) })
		t.Run("RunClaimSteal", func(t *testing.T) { testClaimantGuardRunClaimSteal(t, factory(t)) })
		t.Run("RunClaimSelfIdempotent", func(t *testing.T) { testClaimantGuardRunClaimSelfIdempotent(t, factory(t)) })
		t.Run("RunPromote", func(t *testing.T) { testClaimantGuardRunPromote(t, factory(t)) })
		t.Run("RunReleaseClaim", func(t *testing.T) { testClaimantGuardRunReleaseClaim(t, factory(t)) })
		t.Run("RunComplete", func(t *testing.T) { testClaimantGuardRunComplete(t, factory(t)) })
		t.Run("RunRemoveForNode", func(t *testing.T) { testClaimantGuardRunRemoveForNode(t, factory(t)) })
		t.Run("RunPark", func(t *testing.T) { testClaimantGuardRunPark(t, factory(t)) })
		t.Run("RunForceOverride", func(t *testing.T) { testClaimantGuardRunForceOverride(t, factory(t)) })
		t.Run("UnguardedMutationCarveOuts", func(t *testing.T) { testClaimantGuardUnguardedMutationCarveOuts(t, factory(t)) })
	})
	t.Run("MessageIdempotency", func(t *testing.T) {
		t.Run("InsertOrLookup", func(t *testing.T) { testMessageIdempotencyInsertOrLookup(t, factory(t)) })
		t.Run("InsertOrLookupRace", func(t *testing.T) { testMessageIdempotencyInsertOrLookupRace(t, factory(t)) })
		t.Run("DeleteOlderThan", func(t *testing.T) { testMessageIdempotencyDeleteOlderThan(t, factory(t)) })
	})
	t.Run("ParkResume", func(t *testing.T) {
		t.Run("SweepSelection", func(t *testing.T) { testParkResumeSweepSelection(t, factory(t)) })
		t.Run("MetadataRoundTrip", func(t *testing.T) { testParkResumeMetadataRoundTrip(t, factory(t)) })
		t.Run("ClearsParkedAt", func(t *testing.T) { testParkResumeClearsParkedAt(t, factory(t), rawQuery) })
		t.Run("ParkedDiagnostic", func(t *testing.T) { testParkResumeParkedDiagnostic(t, factory(t)) })
		t.Run("HeldFrameCount", func(t *testing.T) { testParkResumeHeldFrameCount(t, factory(t)) })
		t.Run("RegisterAsyncAckRoundTrip", func(t *testing.T) { testRegisterAsyncAckRoundTrip(t, factory(t)) })
		t.Run("BumpLastProgressAt", func(t *testing.T) { testBumpLastProgressAt(t, factory(t)) })
	})
	t.Run("FrameLifecycle", func(t *testing.T) {
		t.Run("Default", func(t *testing.T) { testFrameLifecycleSerialQueue(t, factory(t)) })
		t.Run("CascadeImmutableRow", func(t *testing.T) { testFrameRowCascadeImmutable(t, factory(t)) })
		t.Run("EndedHeartbeatDoesNotBumpLastProgressAt", func(t *testing.T) { testFrameEndedHeartbeatDoesNotBumpLastProgressAt(t, factory(t)) })
	})
	t.Run("FrameSettlement", func(t *testing.T) {
		t.Run("NoPendingNodes", func(t *testing.T) { testFrameSettlementNoPendingNodes(t, factory(t)) })
		t.Run("HasFailedNode", func(t *testing.T) { testFrameSettlementHasFailedNode(t, factory(t)) })
		t.Run("MarkSourceNodeStale", func(t *testing.T) { testFrameSettlementMarkSourceNodeStale(t, factory(t)) })
		t.Run("MarkSourceNodeStaleRequiredClaimProducers", func(t *testing.T) {
			testMarkSourceNodeStaleCarriesRequiredClaimProducers(t, factory(t))
		})
		t.Run("OrphanDispatches", func(t *testing.T) { testFrameSettlementOrphanDispatches(t, factory(t)) })
	})
	t.Run("ClaimHandleQueries", func(t *testing.T) {
		t.Run("CountByNamedLock", func(t *testing.T) { testClaimHandleCountByNamedLock(t, factory(t)) })
		t.Run("AnchorsAndRepoint", func(t *testing.T) { testClaimHandleAnchorsAndRepoint(t, factory(t)) })
		t.Run("ChildWalk", func(t *testing.T) { testClaimHandleChildWalk(t, factory(t)) })
		t.Run("ListByInstanceAndState", func(t *testing.T) { testClaimHandleListByInstanceAndState(t, factory(t)) })
		t.Run("SurvivesNodeRunDeletion", func(t *testing.T) { testClaimHandleSurvivesNodeRunDeletion(t, factory(t)) })
		t.Run("ProducerLeaseTokenRoundTrip", func(t *testing.T) { testClaimHandleProducerLeaseTokenRoundTrip(t, factory(t)) })
	})
	t.Run("RetentionSweep", func(t *testing.T) {
		t.Run("ClaimHandles", func(t *testing.T) { testRetentionClaimHandleSweep(t, factory(t)) })
		t.Run("FrameTrace", func(t *testing.T) { testRetentionFrameTracePrune(t, factory(t)) })
		t.Run("FramePruneBlobOrphans", func(t *testing.T) { testFramePruneEnrollsScratchAndAttributeBlobOrphans(t, factory(t)) })
		t.Run("DeletePriorCascadeStalesBlobOrphans", func(t *testing.T) { testDeletePriorCascadeStalesEnrollsScratchBlobOrphan(t, factory(t)) })
		t.Run("DropPendingRunBlobOrphans", func(t *testing.T) { testDropPendingRunEnrollsScratchBlobOrphan(t, factory(t)) })
	})
	t.Run("ScratchSpillRoundTrip", func(t *testing.T) {
		t.Run("OverThresholdSpillsThroughRealBackend", func(t *testing.T) { testScratchOverThresholdSpillsThroughRealBackend(t, factory(t)) })
		t.Run("AtOrBelowThresholdStaysInlineThroughRealBackend", func(t *testing.T) { testScratchAtOrBelowThresholdStaysInlineThroughRealBackend(t, factory(t)) })
	})
	t.Run("CascadeWalkerMethods", func(t *testing.T) {
		t.Run("TwoLegClaimPromote", func(t *testing.T) { testTwoLegClaimPromoteContract(t, factory(t)) })
		t.Run("CreateCascadePendingAndFindLatest", func(t *testing.T) { testCreateCascadePendingAndFindLatest(t, factory(t)) })
		t.Run("LockReceiverCascadeNoDeadlock", func(t *testing.T) { testLockReceiverCascade_NoDeadlock(t, factory(t)) })
		t.Run("CreateNonCascadeStaleCarriesForward", func(t *testing.T) { testCreateNonCascadeStaleCarriesForward(t, factory(t)) })
		t.Run("SetRunRequiredStoresReusesStaleRun", func(t *testing.T) { testSetRunRequiredStores_ReusesStaleRun(t, factory(t)) })
	})
	t.Run("LineageQueryByParentRunID", func(t *testing.T) { testLineageQueryByParentRunID(t, factory(t)) })
	t.Run("LineageQueryPaginatesWithCursor", func(t *testing.T) { testLineageQueryPaginatesWithCursor(t, factory(t)) })
	t.Run("LineageCountOlderThanMatchesDelete", func(t *testing.T) { testLineageCountOlderThanMatchesDelete(t, factory(t)) })
	t.Run("APIKeys", func(t *testing.T) { testAPIKeys(t, factory(t)) })
	t.Run("DeploymentCA", func(t *testing.T) { TestDeploymentCA(t, factory(t)) })
	t.Run("TemplatesInsertIdempotent", func(t *testing.T) { testTemplatesInsertIdempotent(t, factory(t)) })
	t.Run("TemplatesListPaginationSurvivesCursorRowDeletion", func(t *testing.T) { testTemplatesListPaginationSurvivesCursorRowDeletion(t, factory(t)) })
}
