apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rimsky.fullname" . }}-control-api
  labels:
    {{- include "rimsky.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-api
spec:
  replicas: {{ .Values.controlapi.replicas }}
  selector:
    matchLabels:
      {{- include "rimsky.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: control-api
  template:
    metadata:
      labels:
        {{- include "rimsky.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: control-api
    spec:
      serviceAccountName: {{ include "rimsky.serviceAccountName" . }}
      containers:
        - name: control-api
          image: "{{ .Values.image.repository }}/control-api:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RIMSKY_DB_URL
              value: {{ .Values.postgres.dsn | quote }}
            - name: RIMSKY_HTTP_ADDR
              value: ":{{ .Values.controlapi.service.port }}"
          ports:
            - name: http
              containerPort: {{ .Values.controlapi.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
