apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rimsky.fullname" . }}-http-node
  labels:
    {{- include "rimsky.labels" . | nindent 4 }}
    app.kubernetes.io/component: http-node
spec:
  replicas: {{ .Values.httpNode.replicas }}
  selector:
    matchLabels:
      {{- include "rimsky.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: http-node
  template:
    metadata:
      labels:
        {{- include "rimsky.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: http-node
    spec:
      serviceAccountName: {{ include "rimsky.serviceAccountName" . }}
      containers:
        - name: http-node
          image: "{{ .Values.image.repository }}/executor-http-node:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RIMSKY_EXECUTOR_HTTP_NODE_HOST
              value: "0.0.0.0"
            - name: RIMSKY_EXECUTOR_HTTP_NODE_PORT
              value: {{ .Values.httpNode.service.port | quote }}
            - name: RIMSKY_EXECUTOR_HTTP_NODE_HTTP_PORT
              value: {{ .Values.httpNode.service.httpPort | quote }}
            - name: RIMSKY_EXECUTOR_STUB_MODE
              value: "1"
          ports:
            - name: grpc
              containerPort: {{ .Values.httpNode.service.port }}
            - name: http
              containerPort: {{ .Values.httpNode.service.httpPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
