apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rimsky.fullname" . }}-sensor-cron
  labels:
    {{- include "rimsky.labels" . | nindent 4 }}
    app.kubernetes.io/component: sensor-cron
spec:
  replicas: {{ .Values.sensorCron.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "rimsky.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: sensor-cron
  template:
    metadata:
      labels:
        {{- include "rimsky.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: sensor-cron
    spec:
      serviceAccountName: {{ include "rimsky.serviceAccountName" . }}
      containers:
        - name: sensor-cron
          image: "{{ .Values.bundledServicesImage.repository }}/sensor-cron:{{ .Values.sensorCron.imageTag | default .Values.bundledServicesImage.tag }}"
          imagePullPolicy: {{ .Values.bundledServicesImage.pullPolicy }}
          env:
            - name: RIMSKY_ENDPOINT
              value: "{{ .Values.rimskyEndpoint | default (printf "http://%s-control-api:8080" (include "rimsky.fullname" .)) }}"
            - name: RIMSKY_SENSOR_CRON_HOST
              value: "0.0.0.0"
            - name: RIMSKY_SENSOR_CRON_PORT
              value: "9081"
          ports:
            - name: grpc
              containerPort: 9081
