apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rimsky.fullname" . }}-supervisor
  labels:
    {{- include "rimsky.labels" . | nindent 4 }}
    app.kubernetes.io/component: supervisor
spec:
  replicas: {{ .Values.supervisor.replicas }}
  selector:
    matchLabels:
      {{- include "rimsky.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: supervisor
  template:
    metadata:
      labels:
        {{- include "rimsky.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: supervisor
    spec:
      serviceAccountName: {{ include "rimsky.serviceAccountName" . }}
      containers:
        - name: supervisor
          image: "{{ .Values.image.repository }}/supervisor:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RIMSKY_DB_URL
              value: {{ .Values.postgres.dsn | quote }}
            - name: RIMSKY_SUPERVISOR_CONFIG
              value: /etc/rimsky/supervisor-config.yml
            - name: RIMSKY_STORES_CONFIG
              value: /etc/rimsky/stores.yml
            - name: RIMSKY_SUPERVISOR_CALLBACK_ADVERTISE_HOST
              value: {{ default (printf "%s-supervisor" (include "rimsky.fullname" .)) .Values.supervisor.callbackAdvertiseHost | quote }}
          volumeMounts:
            - name: supervisor-config
              mountPath: /etc/rimsky/supervisor-config.yml
              subPath: supervisor-config.yml
              readOnly: true
            - name: stores-config
              mountPath: /etc/rimsky/stores.yml
              subPath: stores.yml
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: supervisor-config
          configMap:
            name: {{ include "rimsky.fullname" . }}-supervisor-config
        - name: stores-config
          configMap:
            name: {{ include "rimsky.fullname" . }}-stores-config
