apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rimsky.fullname" . }}-sensor-object-store
  labels:
    {{- include "rimsky.labels" . | nindent 4 }}
    app.kubernetes.io/component: sensor-object-store
spec:
  replicas: {{ .Values.sensorObjectStore.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "rimsky.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: sensor-object-store
  template:
    metadata:
      labels:
        {{- include "rimsky.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: sensor-object-store
    spec:
      serviceAccountName: {{ include "rimsky.serviceAccountName" . }}
      containers:
        - name: sensor-object-store
          image: "{{ .Values.image.repository }}/sensor-object-store:{{ .Values.sensorObjectStore.imageTag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RIMSKY_ENDPOINT
              value: "{{ .Values.rimskyEndpoint | default (printf "http://%s-control-api:8080" (include "rimsky.fullname" .)) }}"
            - name: RIMSKY_SENSOR_OBJECT_STORE_HOST
              value: "0.0.0.0"
            - name: RIMSKY_SENSOR_OBJECT_STORE_PORT
              value: "9083"
            {{- with .Values.sensorObjectStore.stateDSN }}
            - name: RIMSKY_SENSOR_OBJECT_STORE_STATE_DSN
              value: {{ . | quote }}
            {{- end }}
          ports:
            - name: grpc
              containerPort: 9083
