apiVersion: v1
kind: Service
metadata:
  name: {{ include "rimsky.fullname" . }}-sensor-webhook
  labels:
    {{- include "rimsky.labels" . | nindent 4 }}
    app.kubernetes.io/component: sensor-webhook
spec:
  type: ClusterIP
  selector:
    {{- include "rimsky.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sensor-webhook
  ports:
    - name: grpc
      port: 9084
      targetPort: grpc
    - name: http
      port: 9184
      targetPort: http
