apiVersion: v1
kind: Service
metadata:
  name: {{ include "rimsky.fullname" . }}-http-node
  labels:
    {{- include "rimsky.labels" . | nindent 4 }}
    app.kubernetes.io/component: http-node
spec:
  type: {{ .Values.httpNode.service.type }}
  selector:
    {{- include "rimsky.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: http-node
  ports:
    - name: grpc
      port: {{ .Values.httpNode.service.port }}
      targetPort: {{ .Values.httpNode.service.port }}
