apiVersion: v1
kind: Service
metadata:
  name: {{ include "rimsky.fullname" . }}-sensor-http
  labels:
    {{- include "rimsky.labels" . | nindent 4 }}
    app.kubernetes.io/component: sensor-http
spec:
  type: ClusterIP
  selector:
    {{- include "rimsky.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sensor-http
  ports:
    - name: grpc
      port: 9082
      targetPort: grpc
