apiVersion: v1
kind: Service
metadata:
  name: {{ include "rimsky.fullname" . }}-sensor-object-store
  labels:
    {{- include "rimsky.labels" . | nindent 4 }}
    app.kubernetes.io/component: sensor-object-store
spec:
  type: ClusterIP
  selector:
    {{- include "rimsky.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sensor-object-store
  ports:
    - name: grpc
      port: 9083
      targetPort: grpc
