// Copyright © 2026 Fall Guy Consulting.
// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-FallGuy-Commercial

// @decision: env-var-registry

package scan

import (
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var literalPattern = regexp.MustCompile(`"(RIMSKY_[A-Z0-9_]+)"`)

var liveRoots = []string{"cmd", "lib"}

func isLiveGoFile(rel string) bool {
	if !strings.HasSuffix(rel, ".go") || strings.HasSuffix(rel, "_test.go") {
		return false
	}
	parts := strings.Split(filepath.ToSlash(rel), "/")
	for _, p := range parts {
		switch p {
		case "test", "testdata", "testfixture", "storetest", "gen":
			return false
		}
	}
	return true
}

type Read struct {
	Name string
	Site string
}

func LiveReads(repoRoot string) ([]Read, error) {
	sites := map[string]string{}
	for _, root := range liveRoots {
		rootPath := filepath.Join(repoRoot, root)
		err := filepath.WalkDir(rootPath, func(path string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() {
				return nil
			}
			rel, rerr := filepath.Rel(repoRoot, path)
			if rerr != nil {
				return rerr
			}
			if !isLiveGoFile(rel) {
				return nil
			}
			src, rerr := os.ReadFile(path)
			if rerr != nil {
				return rerr
			}
			for _, m := range literalPattern.FindAllStringSubmatch(string(src), -1) {
				name := m[1]
				if existing, ok := sites[name]; !ok || filepath.ToSlash(rel) < existing {
					sites[name] = filepath.ToSlash(rel)
				}
			}
			return nil
		})
		if err != nil {
			return nil, err
		}
	}
	names := make([]string, 0, len(sites))
	for n := range sites {
		names = append(names, n)
	}
	sort.Strings(names)
	out := make([]Read, 0, len(names))
	for _, n := range names {
		out = append(out, Read{Name: n, Site: sites[n]})
	}
	return out, nil
}

func RenderTable(reads []Read) string {
	var b strings.Builder
	b.WriteString("<!-- Generated by `go run ./tools/env-registry`. Do not hand-edit. -->\n")
	b.WriteString("<!-- @decision: env-var-registry -->\n\n")
	b.WriteString("# RIMSKY_* environment variables read by live code\n\n")
	b.WriteString("| Variable | Read site |\n")
	b.WriteString("| --- | --- |\n")
	for _, r := range reads {
		b.WriteString("| `" + r.Name + "` | `" + r.Site + "` |\n")
	}
	return b.String()
}

func ParseTable(src string) []string {
	var names []string
	for _, line := range strings.Split(src, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "| `RIMSKY_") {
			continue
		}
		rest := strings.TrimPrefix(line, "| `")
		end := strings.Index(rest, "`")
		if end < 0 {
			continue
		}
		names = append(names, rest[:end])
	}
	return names
}
