// Copyright © 2026 Fall Guy Consulting.
// Dual-licensed under AGPL-3.0-or-later or a Fall Guy Consulting commercial
// license. See LICENSE.agpl and COPYRIGHT at the repo root.

// runner_emit_message.go — message-emitter-node (`emits_message:`)
// dispatch + terminal-resolution glue.
//
// A node declared with `emits_message: <type>` does not invoke an
// executor. Its dispatch resolves the standard attribute-substitution
// path (so an emit-node can compose its body from upstream attributes,
// instance params, and the triggering signal's payload), then transitions
// directly to terminal/success. The resolved attribute set IS the
// message body; the runtime constructs the envelope and inserts it into
// `rimsky_messages` inside the SAME tx as the node's terminal commit.
//
// Two load-bearing properties live here:
//
//   - Envelope insert is atomic with the sender's terminal-resolution tx.
//     The emit goes through the shared outer tx (`tx persistence.Tx`)
//     that `applyTerminalComplete` already threads to lock release,
//     attribute upsert, and state-machine writes. A rollback after body
//     composition rolls the envelope back too — there is no separate tx,
//     no post-commit closure, no async dispatch.
//
//   - Idempotency on cascade-emit is deterministic on `(node_id,
//     frame_id)`. The `Idempotency-Key` is derived as
//     `cascade-emit:<node_id>:<frame_id>` — node_id is the emit-node's
//     static UUID (immutable across run-row reissue), frame_id is the
//     frame the emit settles in (immutable per dispatch). A supervisor-
//     side hard-failure re-enqueue allocates a fresh `node_run_id` (a
//     new `rimsky_node_runs` row, fresh `gen_random_uuid()` /
//     `uuid.New()`), but `(node_id, frame_id)` is unchanged — the
//     retried emit collapses onto the same dedup row. Keying on the
//     run id (the prior shape) would have re-inserted on every infra
//     retry because the dispatch row's id is regenerated by every
//     stale-mark + AffirmNodeRunRow pair.
//     `MessageIdempotencyTable.InsertOrLookup` is the chokepoint —
//     same code path operator and publisher emits go through — so the
//     "two invocations with the same (node_id, frame_id) produce
//     exactly one envelope" property is structurally satisfied.
//
// @blessed-invariant: cascade-emit idempotency keys on (node_id,
// frame_id), not node_run_id; the run-row identity is regenerated by
// stale-mark cycles and would let infra-retry duplicate envelopes.
//
// @concept: message-emitter-node
// @concept: message

package runtime

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"

	"github.com/rimsky-ai/rimsky-core/lib/foundation/persistence"
	"github.com/rimsky-ai/rimsky-core/lib/foundation/shared"
	"github.com/rimsky-ai/rimsky-core/lib/graph/frame"
)

// EmitMessageDispatchName is the sentinel executor name the scheduler
// stamps on a message-emitter node's dispatch row so the supervisor's
// SelectCandidates picks it up. The runtime's dispatch path (concept:
// message-emitter-node) handles the row BEFORE consulting the executor
// resolver — the executor lookup never fires for emit-nodes — so this
// sentinel is wire-only: it routes the row from queue to supervisor;
// it never reaches a real executor endpoint.
//
// Two constraints shape the value:
//   - It must be in the supervisor's `accepted_executors` list so
//     SelectCandidates admits the row. The supervisor injects it
//     automatically at startup (lib/runtime/supervisor.go).
//   - It must NOT collide with any author-declarable executor name. The
//     "@" prefix is rejected by the template validator's identifier
//     grammar, so authors cannot accidentally shadow it.
//
// @story: cascade-emit
// @concept: message-emitter-node
const EmitMessageDispatchName = "@emit-message"

// emitCascadeMessageInTx constructs the message envelope for a
// message-emitter node, inserts it into `rimsky_messages`, AND enqueues
// the queued frame that will deliver it. Runs inside the caller's outer
// tx (the same tx that `applyTerminalComplete` uses for lock release,
// attribute upsert, and state writes). Returns (newMessageID,
// replayed=false) on a fresh insert; (existingMessageID, replayed=true)
// when the deterministic idempotency-key was already present (e.g. a tx
// retry hit the same `dispatch_id`).
//
// The envelope's fields:
//
//   - `type`: `emitMessage` (the dispatching node's `emits_message:` value).
//   - `sender_kind`: `"instance"` — the structural source-of-claim
//     discriminator for cascade-emit; pairs with sender's `instance:<id>`
//     so the message_idempotencies dedup tuple cannot cross-collide with
//     operator/publisher emits.
//   - `sender`: `instance:<instance_id>`.
//   - `payload`: the resolved attribute set, JSON-marshalled. Per
//     `concept:message-emitter-node` the attribute set IS the body;
//     `validateEmitsMessage` enforces exact-shape match against the
//     destination type's `body_schema` so receivers reading via
//     `{{messages.<type>.<field>}}` see the same field names.
//   - `id`: a fresh UUID. The dedup row carries this id; on a replay,
//     the prior message's id is returned and no envelope row is
//     inserted (per `MessageIdempotencyTable.InsertOrLookup`).
//
// The `Idempotency-Key` is `cascade-emit:<node_id>:<frame_id>`. node_id
// is the emit-node's static UUID; frame_id is the frame this emit
// settles in. A supervisor hard-failure re-enqueue mints a fresh
// `rimsky_node_runs.id` (the prior dispatch_id-keyed shape duplicated
// envelopes on every infra retry), but `(node_id, frame_id)` is
// unchanged across the re-enqueue, so the retry collapses onto the same
// dedup row. (The operator/publisher dedup tuple's
// `sender_kind="instance"` and `sender="instance:<instance_id>"` keep
// this key from cross-colliding with external emits that happen to
// choose the same string.)
//
// Frame enqueue is the structural follow-through that closes the
// cross-frame-coupling loop. Without it the envelope inserts but no
// frame ever opens for it — the next-frame subscribers never wake (the
// running frame F0 belongs to the emit-node and has only its own
// triggering message; `SweepDeliverMessagesForRunningFrames` never
// creates a frame for a pending message). The enqueue mirrors the
// operator-API path at `controlapi.handleCreateMessage` and the
// runtime-synthetic path at `EnqueueSyntheticWakeFrame`: same tx, same
// `EnqueueFrame` call, same FK target. On a replay branch (dedup hit)
// the prior emit attempt already enqueued its frame, so the enqueue
// is skipped — the existing frame is what delivers the existing
// envelope. This preserves the load-bearing property that every
// envelope inserted by this helper has exactly one frame pointing at
// it (no envelope-without-frame, no duplicate frames on retry).
func emitCascadeMessageInTx(
	ctx context.Context,
	tables persistence.Tables,
	tx persistence.Tx,
	instanceID, nodeID, frameID shared.UUID,
	emitMessageType string,
	resolvedAttrs map[string]any,
) (shared.UUID, bool, error) {
	if instanceID == (shared.UUID{}) {
		return shared.UUID{}, false, fmt.Errorf("emitCascadeMessageInTx: instance_id required")
	}
	if nodeID == (shared.UUID{}) {
		return shared.UUID{}, false, fmt.Errorf("emitCascadeMessageInTx: node_id required")
	}
	if frameID == (shared.UUID{}) {
		return shared.UUID{}, false, fmt.Errorf("emitCascadeMessageInTx: frame_id required")
	}
	if emitMessageType == "" {
		return shared.UUID{}, false, fmt.Errorf("emitCascadeMessageInTx: emits_message type required")
	}
	// @constraint: serialize the resolved attribute set as the message
	// body. nil/empty resolves to `{}` (a body shape that's structurally
	// valid JSON but carries no fields) rather than `null` — receivers
	// walking `payload.<field>` expect an object envelope.
	if resolvedAttrs == nil {
		resolvedAttrs = map[string]any{}
	}
	body, err := json.Marshal(resolvedAttrs)
	if err != nil {
		return shared.UUID{}, false, fmt.Errorf("emitCascadeMessageInTx: marshal body: %w", err)
	}

	idempotencyKey := fmt.Sprintf("cascade-emit:%s:%s", nodeID.String(), frameID.String())
	senderKind := "instance"
	sender := "instance:" + instanceID.String()

	// @deliberate: reserve a candidate message id. The idempotency
	// table returns the actual id to use (either this fresh one on a
	// clean insert, or the previously-recorded one on replay).
	candidateID := shared.UUID(uuid.New())

	dedupRow, inserted, err := tables.MessageIdempotencies().InsertOrLookup(ctx, tx, persistence.MessageIdempotencyRow{
		InstanceID: instanceID,
		SenderKind: senderKind,
		Sender:     sender,
		// @deliberate: cascade-emit has no per-caller "subject" — the
		// sender's `instance:<id>` already provides isolation among
		// instances.
		SenderSubject:  "",
		IdempotencyKey: idempotencyKey,
		MessageID:      candidateID,
	})
	if err != nil {
		return shared.UUID{}, false, fmt.Errorf("emitCascadeMessageInTx: idempotency upsert: %w", err)
	}
	if !inserted {
		// @deliberate: replay — a prior emit-attempt for this
		// dispatch_id already landed an envelope row. Return the
		// original id; the caller's downstream observers (event log,
		// cascade walker) can use it just as if this attempt had
		// succeeded. No second envelope row.
		return dedupRow.MessageID, true, nil
	}

	enqueueReq := persistence.EnqueueMessageRequest{
		ID:         candidateID,
		InstanceID: instanceID,
		Type:       emitMessageType,
		Sender:     sender,
		SenderKind: senderKind,
		Payload:    body,
	}
	if err := EnqueueMessage(ctx, tx, tables.Messages(), enqueueReq); err != nil {
		return shared.UUID{}, false, fmt.Errorf("emitCascadeMessageInTx: insert envelope: %w", err)
	}
	// @constraint: queue the frame that will deliver this envelope.
	// Same outer tx keeps {envelope, frame} atomic — a rollback after
	// this point rolls both back; a crash between the two is
	// impossible. Without this enqueue the envelope would stay pending
	// forever (the delivery sweep only iterates RUNNING frames and
	// never creates new ones).
	// @story: cascade-emit
	// @story: cross-frame-coupling
	// @story: one-message-per-frame
	if _, err := frame.EnqueueFrame(ctx, tables, tx, instanceID, candidateID); err != nil {
		return shared.UUID{}, false, fmt.Errorf("emitCascadeMessageInTx: enqueue frame: %w", err)
	}
	return candidateID, false, nil
}
