// Copyright © 2026 Fall Guy Consulting.
// Licensed under the Apache License, Version 2.0. See LICENSE.apache at the
// repo root, or http://www.apache.org/licenses/LICENSE-2.0.

package main

import (
	"os"
	"strings"
	"testing"
)

func TestSpliceGoBeforePackage(t *testing.T) {
	body := []byte("package foo\n\nfunc Bar() {}\n")
	out := splice(body, apacheHeaderGo, kindGo)
	if !strings.HasPrefix(string(out), apacheHeaderGo) {
		t.Errorf("header should be at top, got: %q", string(out)[:60])
	}
	if !strings.Contains(string(out), "package foo") {
		t.Errorf("package decl missing")
	}
}

func TestSpliceGoPackageDocImmediatelyBeforePackage(t *testing.T) {
	body := []byte("// Package foo does X.\npackage foo\n")
	out := splice(body, apacheHeaderGo, kindGo)
	// Header must come before the package-doc comment so go/parser still
	// associates the doc with `package foo`. Because the splice puts header
	// first then a blank line, the package doc remains contiguous with `package`.
	lines := strings.Split(string(out), "\n")
	pkgIdx := -1
	for i, ln := range lines {
		if strings.HasPrefix(ln, "package ") {
			pkgIdx = i
			break
		}
	}
	if pkgIdx <= 0 {
		t.Fatalf("package decl not found")
	}
	if !strings.HasPrefix(lines[pkgIdx-1], "// Package foo") {
		t.Errorf("package-doc comment should be immediately above package, got %q", lines[pkgIdx-1])
	}
}

func TestSpliceGoPreservesGeneratedMarker(t *testing.T) {
	body := []byte("// Code generated by foo. DO NOT EDIT.\npackage foo\n")
	out := splice(body, apacheHeaderGo, kindGo)
	if !strings.HasPrefix(string(out), "// Code generated") {
		t.Errorf("generated marker should remain on top, got: %q", string(out)[:40])
	}
	if !strings.Contains(string(out), apacheHeaderGo) {
		t.Errorf("header should be present after generated marker")
	}
}

func TestSpliceTSPreservesShebang(t *testing.T) {
	body := []byte("#!/usr/bin/env node\nimport x from 'y';\n")
	out := splice(body, apacheHeaderTS, kindTS)
	if !strings.HasPrefix(string(out), "#!/usr/bin/env node\n") {
		t.Errorf("shebang should remain on top, got: %q", string(out)[:30])
	}
	if !strings.Contains(string(out), apacheHeaderTS) {
		t.Errorf("header should be present after shebang")
	}
}

func TestSpliceProtoOnTop(t *testing.T) {
	// Issue #1's motivating case: stamper must put the header above `syntax`,
	// not after it. detectHeader's 10-line window should still find the marker.
	body := []byte(`syntax = "proto3";

package x;
`)
	out := splice(body, apacheHeaderProto, kindProto)
	if !strings.HasPrefix(string(out), apacheHeaderProto) {
		t.Errorf("header should be at the very top, got: %q", string(out)[:60])
	}
	first := strings.SplitN(string(out), "\n", 2)[0]
	if strings.HasPrefix(first, "syntax") {
		t.Errorf("syntax line should NOT be on top after splice")
	}
}

func TestSpliceProtoWithLeadingDocsStillTop(t *testing.T) {
	// A proto with leading documentation already on top — header still goes above.
	body := []byte("// SomeDoc\nsyntax = \"proto3\";\n")
	out := splice(body, apacheHeaderProto, kindProto)
	if !strings.HasPrefix(string(out), apacheHeaderProto) {
		t.Errorf("header should be at the very top, got: %q", string(out)[:60])
	}
}

func TestSpliceSQL(t *testing.T) {
	body := []byte("-- some pre-existing comment\nCREATE TABLE foo (id INT);\n")
	out := splice(body, apacheHeaderSQL, kindSQL)
	if !strings.HasPrefix(string(out), apacheHeaderSQL) {
		t.Errorf("SQL header should be at top, got: %q", string(out)[:50])
	}
}

func TestSpliceShellPreservesShebang(t *testing.T) {
	body := []byte("#!/bin/bash\nset -e\necho hi\n")
	out := splice(body, apacheHeaderShell, kindShell)
	if !strings.HasPrefix(string(out), "#!/bin/bash\n") {
		t.Errorf("shebang should remain on top, got: %q", string(out)[:30])
	}
	if !strings.Contains(string(out), apacheHeaderShell) {
		t.Errorf("header should be present after shebang")
	}
}

func TestSpliceShellEnvShebang(t *testing.T) {
	body := []byte("#!/usr/bin/env bash\necho hi\n")
	out := splice(body, apacheHeaderShell, kindShell)
	if !strings.HasPrefix(string(out), "#!/usr/bin/env bash\n") {
		t.Errorf("env shebang should remain on top, got: %q", string(out)[:40])
	}
}

func TestSpliceShellWithoutShebang(t *testing.T) {
	body := []byte("set -e\necho hi\n")
	out := splice(body, apacheHeaderShell, kindShell)
	if !strings.HasPrefix(string(out), apacheHeaderShell) {
		t.Errorf("header should be at top when no shebang, got: %q", string(out)[:60])
	}
}

func TestSpliceIdempotency(t *testing.T) {
	// Running stamp twice produces the same output: stampHeaders only stamps
	// files lacking a header (detectHeader returns true if the marker is
	// present). We verify by checking that detectHeader reports hasHeader=true
	// after one splice.
	dir := t.TempDir()
	cases := []struct {
		name   string
		body   string
		header string
		kind   sourceKind
	}{
		{"go", "package foo\n", apacheHeaderGo, kindGo},
		{"ts", "import x from 'y';\n", apacheHeaderTS, kindTS},
		{"proto", "syntax = \"proto3\";\n", apacheHeaderProto, kindProto},
		{"sql", "CREATE TABLE x();\n", apacheHeaderSQL, kindSQL},
		{"shell", "#!/bin/bash\necho\n", apacheHeaderShell, kindShell},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			path := dir + "/" + tc.name
			out := splice([]byte(tc.body), tc.header, tc.kind)
			if err := writeTestFile(path, out); err != nil {
				t.Fatalf("write: %v", err)
			}
			has, _, _, err := detectHeader(path)
			if err != nil {
				t.Fatalf("detect: %v", err)
			}
			if !has {
				t.Errorf("after splice, detectHeader should report hasHeader=true; first 200 bytes: %q", string(out)[:min(200, len(out))])
			}
		})
	}
}

func TestDetectHeaderApacheVsAGPL(t *testing.T) {
	dir := t.TempDir()
	apa := dir + "/a.go"
	if err := writeTestFile(apa, []byte(apacheHeaderGo+"\npackage x\n")); err != nil {
		t.Fatal(err)
	}
	agp := dir + "/g.go"
	if err := writeTestFile(agp, []byte(agplHeaderGo+"\npackage x\n")); err != nil {
		t.Fatal(err)
	}
	{
		has, isApa, isAgp, err := detectHeader(apa)
		if err != nil {
			t.Fatal(err)
		}
		if !has || !isApa || isAgp {
			t.Errorf("apache header detected wrong: has=%v apa=%v agp=%v", has, isApa, isAgp)
		}
	}
	{
		has, isApa, isAgp, err := detectHeader(agp)
		if err != nil {
			t.Fatal(err)
		}
		if !has || isApa || !isAgp {
			t.Errorf("agpl header detected wrong: has=%v apa=%v agp=%v", has, isApa, isAgp)
		}
	}
}

// writeTestFile is a small test helper.
func writeTestFile(path string, body []byte) error {
	return os.WriteFile(path, body, 0o644)
}
