// Copyright © 2026 Fall Guy Consulting.
// Dual-licensed under AGPL-3.0-or-later or a Fall Guy Consulting commercial
// license. See LICENSE.agpl and COPYRIGHT at the repo root.

package main

import (
	"os"
	"strings"
	"testing"
)

func TestSpliceGoBeforePackage(t *testing.T) {
	body := []byte("package foo\n\nfunc Bar() {}\n")
	out := splice(body, apacheHeaderGo, kindGo)
	if !strings.HasPrefix(string(out), apacheHeaderGo) {
		t.Errorf("header should be at top, got: %q", string(out)[:60])
	}
	if !strings.Contains(string(out), "package foo") {
		t.Errorf("package decl missing")
	}
}

func TestSpliceGoPackageDocImmediatelyBeforePackage(t *testing.T) {
	body := []byte("// Package foo does X.\npackage foo\n")
	out := splice(body, apacheHeaderGo, kindGo)
	lines := strings.Split(string(out), "\n")
	pkgIdx := -1
	for i, ln := range lines {
		if strings.HasPrefix(ln, "package ") {
			pkgIdx = i
			break
		}
	}
	if pkgIdx <= 0 {
		t.Fatalf("package decl not found")
	}
	if !strings.HasPrefix(lines[pkgIdx-1], "// Package foo") {
		t.Errorf("package-doc comment should be immediately above package, got %q", lines[pkgIdx-1])
	}
}

func TestSpliceGoPreservesGeneratedMarker(t *testing.T) {
	body := []byte("// Code generated by foo. DO NOT EDIT.\npackage foo\n")
	out := splice(body, apacheHeaderGo, kindGo)
	if !strings.HasPrefix(string(out), "// Code generated") {
		t.Errorf("generated marker should remain on top, got: %q", string(out)[:40])
	}
	if !strings.Contains(string(out), apacheHeaderGo) {
		t.Errorf("header should be present after generated marker")
	}
}

func TestSpliceTSPreservesShebang(t *testing.T) {
	body := []byte("#!/usr/bin/env node\nimport x from 'y';\n")
	out := splice(body, apacheHeaderTS, kindTS)
	if !strings.HasPrefix(string(out), "#!/usr/bin/env node\n") {
		t.Errorf("shebang should remain on top, got: %q", string(out)[:30])
	}
	if !strings.Contains(string(out), apacheHeaderTS) {
		t.Errorf("header should be present after shebang")
	}
}

func TestSpliceProtoOnTop(t *testing.T) {
	body := []byte(`syntax = "proto3";

package x;
`)
	out := splice(body, apacheHeaderProto, kindProto)
	if !strings.HasPrefix(string(out), apacheHeaderProto) {
		t.Errorf("header should be at the very top, got: %q", string(out)[:60])
	}
	first := strings.SplitN(string(out), "\n", 2)[0]
	if strings.HasPrefix(first, "syntax") {
		t.Errorf("syntax line should NOT be on top after splice")
	}
}

func TestSpliceProtoWithLeadingDocsStillTop(t *testing.T) {
	body := []byte("// SomeDoc\nsyntax = \"proto3\";\n")
	out := splice(body, apacheHeaderProto, kindProto)
	if !strings.HasPrefix(string(out), apacheHeaderProto) {
		t.Errorf("header should be at the very top, got: %q", string(out)[:60])
	}
}

func TestSpliceSQL(t *testing.T) {
	body := []byte("-- some pre-existing comment\nCREATE TABLE foo (id INT);\n")
	out := splice(body, apacheHeaderSQL, kindSQL)
	if !strings.HasPrefix(string(out), apacheHeaderSQL) {
		t.Errorf("SQL header should be at top, got: %q", string(out)[:50])
	}
}

func TestSpliceShellPreservesShebang(t *testing.T) {
	body := []byte("#!/bin/bash\nset -e\necho hi\n")
	out := splice(body, apacheHeaderShell, kindShell)
	if !strings.HasPrefix(string(out), "#!/bin/bash\n") {
		t.Errorf("shebang should remain on top, got: %q", string(out)[:30])
	}
	if !strings.Contains(string(out), apacheHeaderShell) {
		t.Errorf("header should be present after shebang")
	}
}

func TestSpliceShellEnvShebang(t *testing.T) {
	body := []byte("#!/usr/bin/env bash\necho hi\n")
	out := splice(body, apacheHeaderShell, kindShell)
	if !strings.HasPrefix(string(out), "#!/usr/bin/env bash\n") {
		t.Errorf("env shebang should remain on top, got: %q", string(out)[:40])
	}
}

func TestSpliceShellWithoutShebang(t *testing.T) {
	body := []byte("set -e\necho hi\n")
	out := splice(body, apacheHeaderShell, kindShell)
	if !strings.HasPrefix(string(out), apacheHeaderShell) {
		t.Errorf("header should be at top when no shebang, got: %q", string(out)[:60])
	}
}

func TestSpliceIdempotency(t *testing.T) {
	dir := t.TempDir()
	cases := []struct {
		name   string
		body   string
		header string
		kind   sourceKind
	}{
		{"go", "package foo\n", apacheHeaderGo, kindGo},
		{"ts", "import x from 'y';\n", apacheHeaderTS, kindTS},
		{"proto", "syntax = \"proto3\";\n", apacheHeaderProto, kindProto},
		{"sql", "CREATE TABLE x();\n", apacheHeaderSQL, kindSQL},
		{"shell", "#!/bin/bash\necho\n", apacheHeaderShell, kindShell},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			path := dir + "/" + tc.name
			out := splice([]byte(tc.body), tc.header, tc.kind)
			if err := writeTestFile(path, out); err != nil {
				t.Fatalf("write: %v", err)
			}
			has, _, _, err := detectHeader(path)
			if err != nil {
				t.Fatalf("detect: %v", err)
			}
			if !has {
				t.Errorf("after splice, detectHeader should report hasHeader=true; first 200 bytes: %q", string(out)[:min(200, len(out))])
			}
		})
	}
}

func TestDetectHeaderApacheVsAGPL(t *testing.T) {
	dir := t.TempDir()
	apa := dir + "/a.go"
	if err := writeTestFile(apa, []byte(apacheHeaderGo+"\npackage x\n")); err != nil {
		t.Fatal(err)
	}
	agp := dir + "/g.go"
	if err := writeTestFile(agp, []byte(agplHeaderGo+"\npackage x\n")); err != nil {
		t.Fatal(err)
	}
	{
		has, isApa, isAgp, err := detectHeader(apa)
		if err != nil {
			t.Fatal(err)
		}
		if !has || !isApa || isAgp {
			t.Errorf("apache header detected wrong: has=%v apa=%v agp=%v", has, isApa, isAgp)
		}
	}
	{
		has, isApa, isAgp, err := detectHeader(agp)
		if err != nil {
			t.Fatal(err)
		}
		if !has || isApa || !isAgp {
			t.Errorf("agpl header detected wrong: has=%v apa=%v agp=%v", has, isApa, isAgp)
		}
	}
}

func TestStampReplacesWrongKindHeader(t *testing.T) {
	dir := t.TempDir()
	path := dir + "/x.go"
	orig := apacheHeaderGo + "\n// Package x does things.\npackage x\n\nfunc F() {}\n"
	if err := writeTestFile(path, []byte(orig)); err != nil {
		t.Fatal(err)
	}
	f := fileEntry{relPath: "x.go", absPath: path, kind: kindGo, classification: classAGPL}
	if err := stampOne(f, true); err != nil {
		t.Fatalf("stampOne: %v", err)
	}
	s := readFileString(t, path)
	if !strings.HasPrefix(s, agplHeaderGo) {
		t.Errorf("expected AGPL header at top, got:\n%s", s[:min(160, len(s))])
	}
	if strings.Contains(s, "Licensed under the Apache License") {
		t.Errorf("old Apache header should be gone:\n%s", s)
	}
	for _, want := range []string{"// Package x does things.", "package x", "func F() {}"} {
		if !strings.Contains(s, want) {
			t.Errorf("body must be preserved; missing %q:\n%s", want, s)
		}
	}
	if strings.Count(s, "Copyright © 2026") != 1 {
		t.Errorf("exactly one copyright line expected:\n%s", s)
	}
}

func TestStampReplacePreservesGeneratedMarker(t *testing.T) {
	dir := t.TempDir()
	path := dir + "/g.go"
	orig := "// Code generated by foo. DO NOT EDIT.\n" + apacheHeaderGo + "\npackage x\n"
	if err := writeTestFile(path, []byte(orig)); err != nil {
		t.Fatal(err)
	}
	f := fileEntry{relPath: "g.go", absPath: path, kind: kindGo, classification: classAGPL}
	if err := stampOne(f, true); err != nil {
		t.Fatalf("stampOne: %v", err)
	}
	s := readFileString(t, path)
	if !strings.HasPrefix(s, "// Code generated by foo. DO NOT EDIT.\n") {
		t.Errorf("generated marker must stay on top:\n%s", s[:min(120, len(s))])
	}
	if !strings.Contains(s, agplHeaderGo) {
		t.Errorf("AGPL header missing:\n%s", s)
	}
	if strings.Contains(s, "Apache License") {
		t.Errorf("old Apache header should be gone:\n%s", s)
	}
}

func TestVerifyHeadersFlagsContradictoryMarkers(t *testing.T) {
	dir := t.TempDir()
	path := dir + "/mixed.go"
	body := agplHeaderGo +
		"\n// SPDX-License-Identifier: Apache-2.0\n" +
		"\npackage x\n"
	if err := writeTestFile(path, []byte(body)); err != nil {
		t.Fatalf("write: %v", err)
	}
	f := fileEntry{relPath: "mixed.go", absPath: path, kind: kindGo, classification: classAGPL}
	vs := verifyHeaders([]fileEntry{f})
	if len(vs) != 1 {
		t.Fatalf("expected exactly one violation, got %d: %+v", len(vs), vs)
	}
	if !strings.Contains(vs[0].message, "contradictory") {
		t.Errorf("violation message should call out contradictory markers, got %q", vs[0].message)
	}
}

func TestStampOneStripsMixedMarkersAndEmitsSingleHeader(t *testing.T) {
	dir := t.TempDir()
	path := dir + "/mixed.go"
	body := agplHeaderGo +
		"\n// SPDX-License-Identifier: Apache-2.0\n" +
		"\npackage x\n\nfunc F() {}\n"
	if err := writeTestFile(path, []byte(body)); err != nil {
		t.Fatalf("write: %v", err)
	}
	f := fileEntry{relPath: "mixed.go", absPath: path, kind: kindGo, classification: classAGPL}
	if err := stampOne(f, true); err != nil {
		t.Fatalf("stampOne: %v", err)
	}
	s := readFileString(t, path)
	if !strings.HasPrefix(s, agplHeaderGo) {
		t.Errorf("expected AGPL header at top, got:\n%s", s[:min(200, len(s))])
	}
	if strings.Contains(s, "SPDX-License-Identifier: Apache-2.0") {
		t.Errorf("stale Apache SPDX line should be stripped:\n%s", s)
	}
	for _, want := range []string{"package x", "func F() {}"} {
		if !strings.Contains(s, want) {
			t.Errorf("body must be preserved; missing %q:\n%s", want, s)
		}
	}
	if got := strings.Count(s, "Copyright © 2026"); got != 1 {
		t.Errorf("exactly one copyright line expected, got %d:\n%s", got, s)
	}
}

func TestStampHeadersIdempotentOnMixedMarkerRecovery(t *testing.T) {
	dir := t.TempDir()
	path := dir + "/mixed.go"
	body := agplHeaderGo +
		"\n// SPDX-License-Identifier: Apache-2.0\n" +
		"\npackage x\n\nfunc F() {}\n"
	if err := writeTestFile(path, []byte(body)); err != nil {
		t.Fatalf("write: %v", err)
	}
	f := fileEntry{relPath: "mixed.go", absPath: path, kind: kindGo, classification: classAGPL}
	stamped, err := stampHeaders([]fileEntry{f})
	if err != nil {
		t.Fatalf("stampHeaders (first pass): %v", err)
	}
	if stamped != 1 {
		t.Errorf("first pass should stamp exactly 1 file, got %d", stamped)
	}
	afterFirst := readFileString(t, path)

	stamped2, err := stampHeaders([]fileEntry{f})
	if err != nil {
		t.Fatalf("stampHeaders (second pass): %v", err)
	}
	if stamped2 != 0 {
		t.Errorf("second pass should be a no-op, got stamped=%d", stamped2)
	}
	afterSecond := readFileString(t, path)
	if afterFirst != afterSecond {
		t.Errorf("second pass changed the file (re-stamp should be idempotent):\n---first---\n%s\n---second---\n%s", afterFirst, afterSecond)
	}
}

func TestDetectHeaderRecognizesSPDXShortForm(t *testing.T) {
	dir := t.TempDir()
	{
		path := dir + "/apache-spdx.go"
		body := "// SPDX-License-Identifier: Apache-2.0\n\npackage x\n"
		if err := writeTestFile(path, []byte(body)); err != nil {
			t.Fatal(err)
		}
		has, isApa, isAgp, err := detectHeader(path)
		if err != nil {
			t.Fatal(err)
		}
		if !has || !isApa || isAgp {
			t.Errorf("apache SPDX header: has=%v apa=%v agp=%v (want true,true,false)", has, isApa, isAgp)
		}
	}
	{
		path := dir + "/agpl-spdx.go"
		body := "// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-FallGuy-Commercial\n\npackage x\n"
		if err := writeTestFile(path, []byte(body)); err != nil {
			t.Fatal(err)
		}
		has, isApa, isAgp, err := detectHeader(path)
		if err != nil {
			t.Fatal(err)
		}
		if !has || isApa || !isAgp {
			t.Errorf("agpl SPDX header: has=%v apa=%v agp=%v (want true,false,true)", has, isApa, isAgp)
		}
	}
}

func TestStripLeadingHeaderTolerantOfBlankBetweenMarkerRuns(t *testing.T) {
	body := []byte(agplHeaderGo +
		"\n// SPDX-License-Identifier: Apache-2.0\n" +
		"\npackage x\n")
	out := stripLeadingHeader(body, kindGo)
	s := string(out)
	if strings.Contains(s, "Copyright © 2026") {
		t.Errorf("AGPL boilerplate should be stripped:\n%s", s)
	}
	if strings.Contains(s, "SPDX-License-Identifier: Apache-2.0") {
		t.Errorf("trailing SPDX marker should also be stripped:\n%s", s)
	}
	if !strings.HasPrefix(s, "package x") {
		t.Errorf("body should start with `package x` after strip, got:\n%s", s)
	}
}

func writeTestFile(path string, body []byte) error {
	return os.WriteFile(path, body, 0o644)
}

func readFileString(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(b)
}
