// Store interface — the rimsky-side contract every store implementation
// satisfies. Per spec docs/history/2026-04-27-stores-redesign-v3-design.md
// §3 (principles) and §4 (protocol surface), as amended by
// docs/history/2026-04-30-stores-protocol-cleanup-design.md (store-
// internal-vocabulary excision).
//
// In v3 the standard store implementations live in standalone binaries
// under stores/ and rimsky talks to them via the gRPC client in
// core/store/remote/. Type assertions to a concrete store from any
// rimsky package are forbidden — the Store interface is the only
// contract.

package store

import "context"

// Store is the universal interface every store implementation satisfies.
//
// Four runtime verbs (Open / Commit / Abandon / Release) plus one
// startup-handshake verb (Capabilities). Each verb carries a
// rimsky-generated claim_id (per spec §4.2). The store may key its
// internal state by claim_id, by address, by both, or by neither.
//
// Store disposition (what Commit / Abandon mean for the store's own
// state — publish staging, delete an items-table row, release-to-back,
// etc.) is governed entirely by per-store config. Rimsky carries only
// the success/failure binary: success → Commit; failure → Abandon.
//
// @blessed-invariant 9a: Lock state lives only in the persistence layer.
//
//	No Store implementation persists lock state. Stores may persist
//	*data* state (e.g. items-table flips, staging metadata), but the
//	question "is anyone holding lock X" is answered exclusively by
//	rimsky_lock_holders (managed via core/persistence/<driver>/lock_holders.go).
//
// @blessed-invariant 9b: Stores do not internally serialize on
// lock-shaped predicates. The reader-lease serialization pattern is not
// a valid implementation choice for staged_async; honest support
// requires snapshot delegation or native MVCC pass-through.
type Store interface {
	// Name returns the operator-configured store name (matches
	// stores.<name> in rimsky.yml). Rimsky-side identifier; not
	// transported over the wire.
	Name() string

	// Capabilities reports the store's advertised capability struct.
	// Called once per store per rimsky process at startup; rimsky
	// caches the result and validates it against the operator's
	// declared expectation (per spec §6.2).
	Capabilities(ctx context.Context) (Capabilities, error)

	// Open creates whatever store-internal state the (intent,
	// write_semantics) combination requires (staging area, snapshot,
	// MVCC transaction, picked-item flip, or nothing) and returns the
	// store-supplied address the executor will use on the data path.
	// The supervisor calls Open inside the rimsky-side acquisition
	// transaction (per spec §7.3 step 4); the store's own state
	// mutation runs in its own transaction, decoupled.
	//
	// claim_id is generated by the supervisor before the call; the
	// store may record it before any state mutation so its sweep can
	// identify orphans.
	//
	// Stores that may have nothing to give right now (e.g. an empty
	// items-table queue) return OpenOutcome{Available: false}. Rimsky
	// rolls back the dispatch tx and may retry on the next scheduler
	// tick. Store-side faults flow as gRPC error status codes (or
	// wrapped Go errors), not as Available: false.
	Open(ctx context.Context, claimID ClaimID, spec ClaimSpec) (OpenOutcome, error)

	// Commit signals that the consumer of the claim succeeded. The
	// store decides what to do with its own state (publish staging
	// into live, delete the items-table row, release-to-back, etc.)
	// per the store's own configuration. For direct rw, typically a
	// no-op.
	Commit(ctx context.Context, claimID ClaimID, region []byte, address []byte) error

	// Abandon signals that the consumer of the claim failed. The
	// store decides what to do with its own state per its own
	// configuration. Not called for read-only claims and not called
	// by the orphan reaper in v3 default behavior (per spec §7.5).
	// address may be empty when Open's response was lost.
	Abandon(ctx context.Context, claimID ClaimID, region []byte, address []byte) error

	// Release tears down store-internal read state created at Open.
	// Direct stores typically no-op; relevant when the store
	// registered store-side state at Open (staged_async, etc.).
	Release(ctx context.Context, claimID ClaimID, region []byte, address []byte) error

	// Lifecycle events (per docs/specs/2026-05-01-control-plane-and-
	// store-lifecycle-design.md §4.1 / §5). All stores implement all
	// six; stores that don't care just return nil from each method.
	// Idempotent: calling the same event for the same scope twice
	// produces the same observable state.
	OnTemplateRegistered(ctx context.Context, templateID string) error
	OnTemplateDeployed(ctx context.Context, templateID string) error
	OnTemplateUndeployed(ctx context.Context, templateID string) error
	OnTemplateDeregistered(ctx context.Context, templateID string) error
	OnInstanceCreated(ctx context.Context, templateID, instanceID string) error
	OnInstanceTerminated(ctx context.Context, templateID, instanceID string) error
}
